language: r
cache: packages
r_github_packages:
- yonicd/covrpage
- r-lib/pkgdown
after_success:
- Rscript -e 'covr::codecov()'
- Rscript -e 'devtools::install(); covrpage::covrpage_ci()'
- Rscript -e 'pkgdown::build_site()'
after_failure:
- Rscript -e 'devtools::install(); covrpage::covrpage_ci()'
- Rscript -e 'pkgdown::build_site()'
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GH_KEY"
  keep-history: true
  local-dir: docs
  on:
    branch: master
env:
  global:
    secure: k3nYE+OrMhlKSNX03Yz5P/IA0ZR7tqasPRxqeGkeDPZXfQjVOr1ey7xyb+yCfbAWRuLWsAv+XiRroY4NUTAT+g2GOf/UOMNWe2dCSmKX3NK00gTNtRUUo7tnLennhO9OkQ093vPyXqKdUWLGtijWm9Ar3Tnmp5LCGinZ9JY2a2sGT69sMW9CF9vLvWzbRz4w5rpFoTS4+kxBBEqR1LLfMrnyPJRtfPc3k3qhieCi8P1LeLyS0ybj//J/NTfr3U9F3Cbi1aiFFKT7/PueubkjE82Xz9ycpSxJ+9ZBG1RzYB/ZhPbo3m9ycBsmLdcsYPnVSemGqfuq2vUl2WyQFwXdlKWsQ1aNmnvdpIUmJ09Dth7BmhzsKg7xpLVEGJmj9MTQBg8n4vrCMfuvsK49wK4nb0A67Gec+LYLe2cUAJf8zWKuPelZBm76zrHGmO1hnoOt+5FHbhj3pFPrxJuuhwInBRlUXa0ElLsf+ugCcJvKzFGcR8oMfiwu6J9vCAOr9WhaHKk12J9ij7J/28RnwQrGuvTWRKFdqEKwRQG3MrY0OZo2aTOuS1z8qWWBxeLn5/lBJg9NCuu4brls6A7ZJCYBYHPJVOOqJ/FJrSzSOaVjxS0EKZ/BQcGc0BE4RscHYJH3gGj5QkZtNneFxHF1GdkUmbd/X0ZAGi2H7Z4eWvc21K8=
