language: r
cache: packages
r_github_packages:
- yonicd/covrpage
- metrumresearchgroup/pkgdown
os:
- linux
- osx
after_success:
- Rscript -e 'covr::codecov()'
- Rscript -e 'devtools::install(); covrpage::covrpage_ci()'
- Rscript -e 'pkgdown::build_site()'
after_failure:
- Rscript -e 'devtools::install(); covrpage::covrpage_ci()'
- Rscript -e 'pkgdown::build_site()'
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_PAT"
  keep-history: true
  local-dir: docs
  on:
    branch: master
env:
  global:
    secure: Wx+5XqSOMlNJ0+ftDxRo0+NBMKzEnOkU0GY+rlRnjrAoC7e2rRygvGBSE9VyfPH3/Q0ZHHXk0xsy7gmk+/jg1FrmdT+sybRzqAIFG0GhiHpH/vDO045wYU+jcpkYKXqskFbTzXOlWC8XhIwUQu33136uzuHKXoDiOTKYlJFfXgFFH0UzxdJ1/j0i2desBuKlwFgtAWvEx/OovZSNqUUf4PVzx6iunji7YeihvPEn54eUPlBGOg5ZzrP8cIwsJcoX5dSb+STsXROcFbtV2DnLlusd6NHzxAvlCxf4ELKTfUjy2Blry7Zik2RutSRtDsxTH3029k9m0N5Lu+Oi+faqdLGMgytirUvM13VbTqMHPFz8DRaTEtbPoytMKkL7kHrnSUONmdScsd3GKUp8JtHUSFOhFsAt6L3kqrCbk5LcJaRhXpDMwlL5yQJxsbPif44Ykqxj41kDoqrbXkVp4X2UVAFd8LdTTJ4SRVAiaFzLgOX8wcp/6Uu9p+sleuM91f+VObwOJJYcZ4SHBKCJBsXz9sH027EhjLpa41SO8W2EJbu2srFfTIetY7PJuHMd1T9/fAqfiR4iNN5RJegBPl9+SsfngUV7LzH1zoFTg1iJoRts9ejBkAh5hIScDCV+qjIZ8Jybma0KLngPBLrXrubizLluvxsS7FgNnzEeBTetshI=
