language: r
cache: packages

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'covrpage::covrpage(path = '.',preview = FALSE,vignette = TRUE)'
  - Rscript -e 'pkgdown::build_site()'

r_github_packages: 
  - yonicd/covrpage@2fd720e
  - r-lib/pkgdown

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: master