language: r
cache: packages
r_github_packages:
- yonicd/covrpage
- r-lib/pkgdown
after_success:
- Rscript -e 'covr::codecov()'
- Rscript -e 'devtools::install(); covrpage::covrpage_ci()'
- Rscript -e 'pkgdown::build_site()'
after_failure:
- Rscript -e 'devtools::install(); covrpage::covrpage_ci()'
- Rscript -e 'pkgdown::build_site()'
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GH_KEY"
  keep-history: true
  local-dir: docs
  on:
    branch: master
env:
  global:
  - secure: rUOzTtW7Kmes3pwSUQvm6F7+iSEJLgGk+gh6uxn4aG/ooh97JR2EcmCmoC7g1lyvT9Y3NYwbOVSveL6PxLWxq8SYFbX7UqbFJfOeMc/4DsaPn4JPjTOSI0oNhVnWQRdqh+pTUmRZgQ8HONUGIVCyqKVBP73veLK1U//J0z1BGZpLmziLUAiYKJ0duC+JZETjik9anfFk1X6mvkVJugfhnnbaHmw7899sgoEQVxtn5cJH+CNjbwciR3NsvZ+j/mbW7bocXDmVf3QEzDoEQuOB7D5P3mMEOwQN9pWB1oMz0ET7k427HMzaEWxHzSCKNZSxBGHkiBHGms+DrsBEwJhzHhVQRRhlIDekSC8Cvit1kG2fjEAR7rmQ/kB5DQadfq6AKeXucg4/714Pv6oag4zTthubTH3wqwZoNVkISj2ZUu/qqVGN2rbXUXPu/zUUCk3bIaF281SNWFch1q06q7J2B2T80AMw93CijhrrMgXYIMSolK6M4Kjphw5K8NtBzx42dfJoSJ+aaj+4QcwZP+GhI1tqOVC2RVMlXNaXuujpxghsJSn6FpXXa9qpubehNBpQXRxFYTWwqgdWvAkr9mpaNBWYvsmezTUzxnYAbx8xHPTzxSqJ9nL6fLR/QIL+frOtRRPgb3wssE8X70KqtObm2A9bgrbqLxlTOtwP69eqQBw=
