language: r
cache: packages
r_github_packages:
- yonicd/covrpage
- r-lib/pkgdown
os:
- linux
env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false
  - MAKEFLAGS="-j 2"
  - secure: VGeB1XYbLM3QF6hvP9cPeivrQocvUOtDCWyio5S6sBoNlskvlI1gQKuIkBLxin4XB6tuMI59VaTuMjbgwmYrbD9WcRg+JuP84KgbRCvhyOb51gGLKu62fED1suo8rKLRPl857Qp1FfpxnoN2bayRIM8CWz9i/t55Cy+pImefQeCd7GRvgOiKp46FvC86T5vU/aCx2YJIxnSlhSzbBA+VPAa3yqXusYzQexyH0qw8HDvzCCKVd2FIpB3MX29RqhmPPSw1QYI8NO7cbs0Y+jrdbUVThEAomIcnVvpljngecBY19JJxhUiJP6leq4J77OnpYqDbstIrm6g+vTN9KDQaXXCJc0kfloeIasY7UdhBHwoKA0O0sTRSFweNBTTBZ7GlYerfLbg54hXswC9s7dE+TNtBVQBHkN+dpPEvKTURJ9NEj0rs8hAXEZIUyd3BOoILzpHQ2LFN1ALgcLfXP/GljWTdzNQVQCBBPP+efAieVWeYBLU9mv9Ud3L6ZX8on6GmFLsxCrWrcfLZpPXKgoI4ZrdOLXFmZ/PzHI117+uaOT6tkkUswRqXjCBAVNYm79HXG8YX52plMCMbaWKviH8LFTfQnmb5QLiwt7QrWzOR/KLcWVQn/K0GZUHasJ88iHrNBbjWIjpt0ukoBaTULjiRKYzwdjBKUQ//VDtIx/4NeVw=
before_install: R -q -e 'install.packages(c("remotes", "curl")); remotes::install_github("ropenscilabs/tic");
  tic::prepare_all_stages(); tic::before_install()'
install: R -q -e 'tic::install()'
after_install: R -q -e 'tic::after_install()'
before_script: R -q -e 'tic::before_script()'
script: R -q -e 'tic::script()'
after_success: R -q -e 'tic::after_success()'
after_failure: R -q -e 'tic::after_failure()'
before_deploy: R -q -e 'tic::before_deploy()'
deploy:
  provider: script
  script: R -q -e 'tic::deploy()'
  on:
    all_branches: true
after_deploy: R -q -e 'tic::after_deploy()'
after_script: R -q -e 'tic::after_script()'
