language: r
cache: packages
r_packages:
- rstudioapi
r_github_packages:
- metrumresearchgroup/covrpage
- metrumresearchgroup/pkgdown
os:
- linux
after_success:
- Rscript -e 'covr::codecov()'
- Rscript -e 'devtools::install(); covrpage::covrpage_ci()'
- Rscript -e 'pkgdown::build_site()'
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_PAT"
  keep-history: true
  local-dir: docs
  on:
    branch: master
env:
  global:
    secure: VkKOB1X4CLkuZ2ZSewFoDK9jjXw6i9E/cDPNsHJ+nKme7s/kOoC1llKNJIyYNiuFG/256zKV4TEPfZK++aXQxU7QvrqDU6Oy3TpFfLawcEPiOHBCNNRrY2oMt/BiR2srxAtY56pLM89MUD5FUMYTmUlogBBhrRvMhsZAS9R1oNT5GT75mdm4WP7N5P6lCfiVgbC1yCoNa2KO7SM182VRFtbGGfb5G5LMBdliTsotGeMqFdwA4K9YqbWEQaSLu83jq7iwZEeutLica94AwkndBRwFqKaEeP79zbjZgKLuIBKG+Bov70KB3IK20/k3frE+AAY1JJ3m9GJN0BpFK6PDyOjqPis5HJ+XHzWBX3WOMS6JH+D6Io6WadcKQ8hfr4Id4Z+2w9v+5BBx+PQ1jP45WAuL5qc1EG3UQpr71BPojJ3+EtT9O4RZekjel9lXLOnH2sZD/0IEDaSlo6OGXHSe4lbEveC4qyPUCUO0l8UK6sPlV2DRZmk1lKI7w/2e7xfAS06/EqyOo/T4KfyDuSTnALzKUY2mhZoO0BQREDRIHUbKqf+OtfHt6U2a86TPdWyfz1c8zORTirihpWO8uQTxCxdynjKHmJpI3+EuRNTg/lCu0J9CUEOIxPelWaX0qB7FTsLYMrzrJsBv5acfrarZ+rqu3/3oK02orJepNvZ5itE=
notifications:
  slack:
    secure: MRML3o+LA2nXiQtF9l6p5zX5P7QdSzS4d2/DtiwLA0Gj0G8BZjkSX9v3AROAj0EnvtvMHIvYQuHXZwgARADng4uDtzzg4H88N2pRNmyM/4YAPc/04MZt5Cj0zgAj0e3goR/BMU87OmiusYixY75Fk2vtArUQGlFxVCClXyKHhwV0SC56lH+GIlCxHsyaUlTt4BImGBDyRT/suxihZqqjdjmeoCBroHNQldHayXn+IyttGV5sufUbZv1qWu9IkPg3lbV0y35kYR3bv/yIoDGd34Y64qXV6lxw9o/kmlUARhTi4eDHDDzFwq7jSH7MmlnO7ABwFRVbIaUxFO1b0670QmKRPRVqL53hX0VJoHHCn/xk2AN67i/peR8LfKlvA6qAfQpU2CFFyfx+J57mwSkVPq1qJqXrxPGKPfsL+QIJuWaBFk0KfkJjuENCNS5gNa/9pl6wlM6bxXaUipEB+sSWuFFujbO7bvM/YiOQYZKL9FiU2xDIxO0pXI8Gd1MyH2clfaRfRTHIdMKJLfi/YfvFza//80r91g9B6uzGydPz70TUw2KpGDYzsG4cTI/DkN3BWukzYCVdr7mqYtpEFyZBERe0M+7y7Ia+LMF+3ZUHyMXRpK+LScQoSfI9Mupi+7pDKI23As+W14zpgkLVf60mADr4TPZDvxsXDZFnv72JLcM=
