language: r
cache: packages

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'devtools::install(keep_source=TRUE); covrpage::covrpage_ci()'
  - Rscript -e 'pkgdown::build_site()'

r_github_packages:
  - r-lib/pkgdown
  
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: master
